##################################
# Wallpaper
##################################

preload = ~/.config/hypr/wp/blackmetal.png

wallpaper[]:path = ~/.config/hypr/wp/blackmetal.png
wallpaper[DP-2]:path = ~/.config/hypr/wp/blackmetal.png

ipc = true
splash = false
