# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/wp/blackmetal.png

    blur_passes = 0
    contrast = 1.0
    brightness = 0.6
    vibrancy = 0.0
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# NAME
label {
    monitor =
    text = Jeremie
    color = rgba(236, 238, 227, 0.85)
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 20
    font_family = SF Pro Display Bold
    position = 25, 110
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(236, 238, 227, 0.90)
    font_size = 60
    font_family = SF Pro Display Bold
    position = 30, -8
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(151, 75, 70, 0.95)
    font_size = 19
    font_family = SF Pro Display Bold
    position = 35, -60
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 320, 55
    color = rgba(255, 255, 255, 0.05)
    rounding = 0
    border_size = 1
    border_color = rgba(34, 34, 34, 1)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = 34, -190
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text =     $USER
    color = rgba(193, 193, 193, 0.90)
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 16
    font_family = SF Pro Display Bold
    position = 38, -190
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 1
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    rounding = 0
    outer_color = rgba(34, 34, 34, 1)
    inner_color = rgba(0, 0, 0, 0.85)
    font_color = rgb(236, 238, 227)
    check_color = rgba(95, 135, 135, 1)
    fail_color = rgba(151, 75, 70, 1)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <i><span foreground="##50505099">🔒  Enter Pass</span></i>
    hide_input = false
    position = 34, -268
    halign = center
    valign = center
}
