font_size 16.0
font_family FiraCode Nerd Font

background_opacity 1
background_blur 0
dynamic_background_opacity yes

# Black Metal (khold) Color Scheme
foreground #c1c1c1
background #000000
selection_foreground #c1c1c1
selection_background #222222

# Normal colors
color0  #000000
color1  #974b46
color2  #5f8787
color3  #888888
color4  #999999
color5  #39121b
color6  #5f8787
color7  #c1c1c1

# Bright colors
color8  #505050
color9  #c15d57
color10 #7aa5a5
color11 #aaaaaa
color12 #b3b3b3
color13 #6e4c4c
color14 #7aa5a5
color15 #eceee3

# Cursor colors
cursor #eceee3
cursor_text_color #000000

# URL colors
url_color #5f8787
