##################################
# Wallpaper
##################################

preload = ~/.config/hypr/wp/galaxy-waves.jpg
preload = ~/.config/hypr/wp/desolate-city.jpg

wallpaper[]:path = ~/.config/hypr/wp/galaxy-waves.jpg
wallpaper[DP-2]:path = ~/.config/hypr/wp/desolate-city.jpg


ipc = true
splash = false
