##################################
# Wallpaper
##################################

preload = ~/.config/hypr/wp/gruv.jpg
preload = ~/.config/hypr/wp/gruv-wallhaven-4gmevq.png

wallpaper[]:path = ~/.config/hypr/wp/gruv.jpg
wallpaper[DP-2]:path = ~/.config/hypr/wp/gruv-wallhaven-4gmevq.png

ipc = true
splash = false
