##################################
# Wallpaper
##################################

preload = ~/.config/hypr/wp/clouds-2.png
preload = ~/.config/hypr/wp/snowflakes.jpg

wallpaper[]:path = ~/.config/hypr/wp/clouds-2.png
wallpaper[DP-2]:path = ~/.config/hypr/wp/snowflakes.jpg

ipc = true
splash = false
